---
title: "Project Proposal"
author: "STOR 320.01 Group PLACE_GROUP_NUMBER_HERE (Ex: STOR 320.01 Group 12)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Project Roles

- **Creator:** Noah Wessels
- **Interpreter:** Yunzhou Liu
- **Orator 1:** Camryn Blawas
- **Deliverer:** Noah Howell

# Dataset

[Placement_Data_Full_Class](https://www.kaggle.com/benroshan/factors-affecting-campus-placement/data)

# Initial Questions

- **Question 1:** What is the relationship between gender and placement?
- **Question 2:** Is there any collinearity between variables?
- **Question 3:** Which categorical variables significantly impacts the Employability test result? 
- **Question 4:** Are there any significant differences of salaries between different fields of undergraduate research?
- **Question 5:** How much do one's grades influence post-graduate life (i.e. placement status, salary)?
- **Question 6:** How good of a measure is the employability test of job placement?
- **Question 7:** Do secondary education percentage and higher secondary education percentage have an effect on job placement placement?
- **Question 8:** What is the effect of undergraduate degree type and MBA specialization on salary?